// Annuaire des coopérants de l’IUT de Cumaná.
// Fichier séparé de index.html pour faciliter la maintenance et les mises à jour.
// Attention : ce fichier reste publiquement accessible sur GitHub Pages.
window.COOPERANTS = [
{"gen": 0, "nom": "Bérard", "prenom": "Alain", "periode": "1972 - 1975", "discipline": "Matematicas", "dept": "Directeur", "source": "JMA"},
{"gen": 1, "nom": "??", "prenom": "Gabriel", "periode": "1973-1975", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA"},
{"gen": 1, "nom": "Boussac", "prenom": "Jean-Paul", "periode": "1973 - 1976", "discipline": "Electrónica", "dept": "Electricidad", "source": " JMA, Copains d'avant, Gaceta Oficial 29.985 (18/12/1972)"},
{"gen": 1, "nom": "Dordor", "prenom": "Patrice", "periode": "1973-1975", "discipline": "Mathématiques", "dept": "Electricidad", "source": "JMA, Linkedin"},
{"gen": 1, "nom": "Gibert", "prenom": "Hervé", "periode": "1973 - 1977", "discipline": "Dessin Industriel", "dept": "Electricidad", "source": "PVS & familia, JMA"},
{"gen": 1, "nom": "Montet ", "prenom": "Roland", "periode": "1973-1975", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA"},
{"gen": 1, "nom": "Navarro", "prenom": "Jean-Pierre", "periode": "1973 - 1979", "discipline": "Biologia", "dept": "Chef de Dépt. Biologia", "source": "PVS & familia, JMA, Gaceta Oficial 29.985 (18/12/1972)"},
{"gen": 2, "nom": "Agnier", "prenom": "Jean-Michel", "periode": "1974 - 1981", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA, PVS & familia"},
{"gen": 2, "nom": "Courmont", "prenom": "Didier", "periode": "1974–1976", "discipline": "Electricidad, Mecanica ?", "dept": "Electricidad", "source": "PVS & familia, JMA, Rapport Sénat 1975–1976, Gaceta Oficial 29.985 (18/12/1972)"},
{"gen": 2, "nom": "Darbois", "prenom": "Martin", "periode": "1974 - 1979", "discipline": "Microbiologia", "dept": "Biologia", "source": "JMA, PVS & familia"},
{"gen": 2, "nom": "Dudon ", "prenom": "Alain", "periode": "1974-1978", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA"},
{"gen": 2, "nom": "Gallego", "prenom": "Jean-Michel", "periode": "1974 - 1987", "discipline": "Electricidad", "dept": "Electricidad", "source": "PVS & familia, JMA"},
{"gen": 2, "nom": "Gourmelon", "prenom": "Jean-Jacques", "periode": "1974 - 1976", "discipline": "À confirmer", "dept": "À confirmer", "source": "JMA, Copains d'avant"},
{"gen": 2, "nom": "Grimaldi", "prenom": "Alain", "periode": "1974 - 1977", "discipline": "Biologia", "dept": "Biologia", "source": "PVS & familia, JMA"},
{"gen": 2, "nom": "Lecapelain", "prenom": "Bertrand", "periode": "1974 - 1977", "discipline": "Electricidad", "dept": "Electricidad", "source": "PVS & familia, JMA"},
{"gen": 2, "nom": "Mounier", "prenom": "Patrice", "periode": "1974 - 1977", "discipline": "Electricidad", "dept": "Electricidad", "source": "PVS & familia, JMA"},
{"gen": 2, "nom": "Perrier", "prenom": "Richard", "periode": "1974-1976", "discipline": "Matematicas", "dept": "Electricidad", "source": "JMA, Linkedin"},
{"gen": 2, "nom": "Vagneur", "prenom": "Jean-Louis", "periode": "1974 - 1977", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA"},
{"gen": 2, "nom": "Vignaud", "prenom": "Patrice", "periode": "1975 - 1977", "discipline": "Electronica", "dept": "Electricidad", "source": "Viadeo"},
{"gen": 3, "nom": "Cascarino", "prenom": "Georges", "periode": "1975 - 1979", "discipline": "Biologia", "dept": "Biologia", "source": "PVS & familia, JMA, Linkedin, Copains d'avant"},
{"gen": 3, "nom": "Cavarroc", "prenom": "Jean-Claude", "periode": "1975 - 1977", "discipline": "À confirmer", "dept": "À confirmer", "source": "JMA, Copains d'avant"},
{"gen": 3, "nom": "Chavanne", "prenom": "Didier", "periode": "1975–1978", "discipline": "À confirmer", "dept": "À confirmer", "source": "JMA, Copains d'avant"},
{"gen": 3, "nom": "Chevin", "prenom": "Michel", "periode": "1975 - 1977", "discipline": "Matematicas", "dept": "Basico", "source": "PVS & familia, JMA"},
{"gen": 3, "nom": "Genaud", "prenom": "Bernard", "periode": "1975-1978", "discipline": "Electricidad", "dept": "Electricidad", "source": "JMA"},
{"gen": 3, "nom": "Ranchin", "prenom": "Paul Éric", "periode": "1975–1976", "discipline": "Electricidad", "dept": "Electricidad", "source": "PVS & familia, JMA, Rapport Sénat 1975–1976"},
{"gen": 3, "nom": "Sanz", "prenom": "Richard", "periode": "1975 - 1976", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia, JMA"},
{"gen": 3, "nom": "Sibiril", "prenom": "Sylvie", "periode": "1975 - ", "discipline": "Bioquimica", "dept": "Biologia", "source": "PVS & familia, JMA, PhB"},
{"gen": 4, "nom": "Frichou", "prenom": "Jacques", "periode": "1976–1978", "discipline": "Quimica", "dept": "Quimica", "source": "PVS & familia, Copains d'avant"},
{"gen": 4, "nom": "Labarthe", "prenom": "?", "periode": "1976–1978", "discipline": "A confirmer", "dept": "Biologia o Quimica ?", "source": "PVS & familia, BT"},
{"gen": 4, "nom": "Lefebvre", "prenom": "Thierry", "periode": "1976 - 1981", "discipline": "Electricidad", "dept": "Chef de Dépt. Electricidad", "source": "JMA, PVS& familia, Rapport Sénat 1975–1976"},
{"gen": 4, "nom": "Menny", "prenom": "Michel", "periode": "1976 - 1978", "discipline": "Matematica, Fisica", "dept": "Biologia", "source": "Linkedin"},
{"gen": 5, "nom": "??", "prenom": "David", "periode": "1977 - 1978", "discipline": "À confirmer", "dept": "Electricidad", "source": "JMA"},
{"gen": 5, "nom": "Bouillin", "prenom": "Philippe", "periode": "1977–1978", "discipline": "Biologia", "dept": "Biologia", "source": "PVS & familia"},
{"gen": 5, "nom": "Desprez", "prenom": "Pierre", "periode": "1977 - 1980", "discipline": "Matematicas", "dept": "Basico", "source": "PVS & familia"},
{"gen": 5, "nom": "Frachet", "prenom": "Jean-Pierre", "periode": "1977–1978", "discipline": "Electricidad", "dept": "Electricidad", "source": "PVS & familia"},
{"gen": 5, "nom": "Guillouët", "prenom": "Pascal", "periode": "1977–1978", "discipline": "Dessin Industriel", "dept": "Electricidad", "source": "PVS & familia"},
{"gen": 5, "nom": "Krafft", "prenom": "André", "periode": "1977–1978", "discipline": "À confirmer", "dept": "Biologia", "source": "PVS & familia"},
{"gen": 5, "nom": "Lafforgue", "prenom": "Jacques", "periode": "1977–1978", "discipline": "Matematicas", "dept": "Basico", "source": "PVS & familia"},
{"gen": 5, "nom": "Levieil", "prenom": "Gilles", "periode": "1977–1978", "discipline": "Physique", "dept": "Biologia", "source": "PVS & familia"},
{"gen": 5, "nom": "Martin", "prenom": "Pierre", "periode": "1977 - 1979", "discipline": "À confirmer", "dept": "Quimica", "source": "JMA, PhB"},
{"gen": 5, "nom": "Maurice", "prenom": "Christian", "periode": "1977–1979", "discipline": "À confirmer", "dept": "Quimica", "source": "PhB"},
{"gen": 5, "nom": "Morandat", "prenom": "Roger", "periode": "1977–1978", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia, BT"},
{"gen": 5, "nom": "Niquet", "prenom": "Michel", "periode": "1977–1978 ?", "discipline": "Matematicas", "dept": "Biologia", "source": "PVS & familia, Copains d'avant, Rapport Sénat"},
{"gen": 5, "nom": "Rouquier", "prenom": "Paul", "periode": "1977–1978", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia"},
{"gen": 5, "nom": "Royer", "prenom": "Guy", "periode": "1977-1978", "discipline": "Quimica", "dept": "Biologia", "source": "PVS & familia, PhB"},
{"gen": 5, "nom": "Sabarot", "prenom": "Christian", "periode": "1977–1978", "discipline": "À confirmer", "dept": "Biologia", "source": "PVS & familia"},
{"gen": 5, "nom": "Sirbat", "prenom": "Pierre", "periode": "1977 - 1978", "discipline": "Microbiologia", "dept": "Biologia", "source": "PVS & familia, PhB"},
{"gen": 5, "nom": "Trachez", "prenom": "Bruno", "periode": "1977–1979", "discipline": "Biologia", "dept": "Biologia", "source": "PVS & familia, Copains d'avant, Viadeo, Rapport Sénat"},
{"gen": 5, "nom": "Varon", "prenom": "Jean-Louis", "periode": "1977-1978", "discipline": "À confirmer", "dept": "Electricidad", "source": "PVS & familia"},
{"gen": 5, "nom": "Vogt-Schilb", "prenom": "Philippe", "periode": "1977–1979", "discipline": "Géométrie, Électrotechnique", "dept": "Básico, Electricidad", "source": "PVS & familia"},
{"gen": 6, "nom": "Bonnet", "prenom": "Marc", "periode": "1978–1979", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia"},
{"gen": 6, "nom": "Channet", "prenom": "Olivier", "periode": "1978–1979", "discipline": "À confirmer", "dept": "Electricidad", "source": "BT"},
{"gen": 6, "nom": "Feuillet", "prenom": "Jean Michel", "periode": "1978–1978", "discipline": "Fisica", "dept": "Biologia", "source": "Nelson Albornoz, PVS & familia, BT"},
{"gen": 6, "nom": "Monnier", "prenom": "Éric", "periode": "1978-1979", "discipline": "À confirmer", "dept": "Quimica", "source": "PVS & familia, Source indépendante"},
{"gen": 6, "nom": "Rebaud", "prenom": "Pierre", "periode": "1978-1980", "discipline": "À confirmer", "dept": "Electricidad ?", "source": "BT, JMA"},
{"gen": 6, "nom": "??", "prenom": "Antoine", "periode": "1978-1979", "discipline": "À confirmer", "dept": "Electricidad", "source": "PVS & familia"},
{"gen": 7, "nom": "Bargel", "prenom": "Thierry", "periode": "1979-1980", "discipline": "Microbiologia", "dept": "Biologia", "source": "PhB"},
{"gen": 7, "nom": "Bonneau", "prenom": "Alain", "periode": "1979-1981", "discipline": "Optica - Mecanica - Termodinamica", "dept": "Quimica", "source": "Linkedin"},
{"gen": 7, "nom": "Bottelier", "prenom": "Pierre", "periode": "1979", "discipline": "A confirmer", "dept": "A confirmer", "source": "BT"},
{"gen": 7, "nom": "Soiron", "prenom": "Gilles", "periode": "1979-1980", "discipline": "Electricidad", "dept": "Biologia", "source": "PhB"},
{"gen": 7, "nom": "Trichereau ", "prenom": "Eric", "periode": "1979 - 1980", "discipline": "Mecanica de los fluidos", "dept": "Biologia", "source": "PVS & familia, PhB"},
{"gen": "?", "nom": "Du Terrail", "prenom": "Yves", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia, BT"},
{"gen": "?", "nom": "Moreno", "prenom": "Marc", "periode": "À confirmer", "discipline": "À confirmer", "dept": "Quimica ?", "source": "PVS & familia, BT"},
{"gen": "?", "nom": "Bernard", "prenom": "Jean-Pierre", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia"},
{"gen": "?", "nom": "Borderie", "prenom": "Pierre", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "JMA"},
{"gen": "?", "nom": "Cohades", "prenom": "Bruno", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "JMA"},
{"gen": "?", "nom": "Landry", "prenom": "Christian", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia"},
{"gen": "?", "nom": "Maillet", "prenom": "Didier", "periode": "À confirmer", "discipline": "À confirmer", "dept": "À confirmer", "source": "PVS & familia"},
{"gen": "?", "nom": "Mercier", "prenom": "Pierre", "periode": "À confirmer", "discipline": "Química", "dept": "À confirmer", "source": "PVS & familia, Gaceta Oficial 29.985 (18/12/1972)"}
];
